### ISSUE TITLE
This shouldn't be an integer

### ISSUE THREAD

**Issue by philpandco** [cardstream/OpenCart#1]
https://github.com/cardstream/OpenCart/blob/95c1905e7deae8d729478c8265b71617a7a57706/httpdocs/catalog/controller/payment/cardstream.php#L51

There shouldn't be any (int) on this line, it's rounding the payment total to the nearest whole number (ie £3.14 => £3). There are a few instances of this and one in the callback too. This might have slipped through if using a test product for £1 :)

**Comment by Quacky2200** [comment]
Hi Ben,

I have released fixes for this issue in all branches which will safely convert the payment total and prevent any rounded numbers to a whole number. Whether the format is an integer or string doesn't matter once in the amount format as long as it has converted the amount properly since the integer will get converted to a string as part of the request. Please see the below changes:

### [Branch 3.0.X](https://github.com/cardstream/OpenCart/commit/b9d4ba504d483fdb65fc70c5088cfb9c2efb7b63#diff-a8bc905c0774bbcf7717f2a9387fdcef)
https://github.com/cardstream/OpenCart/blob/b9d4ba504d483fdb65fc70c5088cfb9c2efb7b63/httpdocs/catalog/controller/extension/payment/cardstream.php#L58-L64
https://github.com/cardstream/OpenCart/blob/b9d4ba504d483fdb65fc70c5088cfb9c2efb7b63/httpdocs/catalog/controller/extension/payment/cardstream.php#L162-L168


### [Branch 2.3.x](https://github.com/cardstream/Opencart/tree/2.3.x)
https://github.com/cardstream/OpenCart/blob/5fac83dfd2571088992e2c5a35ee0864ce8cbd86/httpdocs/catalog/controller/extension/payment/cardstream.php#L49-L52
https://github.com/cardstream/OpenCart/blob/5fac83dfd2571088992e2c5a35ee0864ce8cbd86/httpdocs/catalog/controller/extension/payment/cardstream.php#L84-L92
https://github.com/cardstream/OpenCart/blob/5fac83dfd2571088992e2c5a35ee0864ce8cbd86/httpdocs/catalog/controller/extension/payment/cardstream.php#L205-L211


### [Branch 2.2.x](https://github.com/cardstream/Opencart/tree/2.2.x)
https://github.com/cardstream/OpenCart/blob/eca35539b44d710096d9228220d2b89826ce5f6d/httpdocs/catalog/controller/payment/cardstream.php#L60-L66
https://github.com/cardstream/OpenCart/blob/eca35539b44d710096d9228220d2b89826ce5f6d/httpdocs/catalog/controller/payment/cardstream.php#L165-L170

### [Branch 2.0.x](https://github.com/cardstream/Opencart/tree/2.0.x)
https://github.com/cardstream/OpenCart/blob/5d5ab942e6fc18874170a5e7749f87dbf9c2d9e2/httpdocs/catalog/controller/payment/cardstream.php#L62-L67
https://github.com/cardstream/OpenCart/blob/5d5ab942e6fc18874170a5e7749f87dbf9c2d9e2/httpdocs/catalog/controller/payment/cardstream.php#L165-L170


### [Branch 1.5.6.4](https://github.com/cardstream/Opencart/tree/1.5.6.4)
https://github.com/cardstream/OpenCart/blob/eb4fa6202274a416ccd7035ecf75c6c9a0232373/httpdocs/catalog/controller/payment/cardstream.php#L34-L37
https://github.com/cardstream/OpenCart/blob/eb4fa6202274a416ccd7035ecf75c6c9a0232373/httpdocs/catalog/controller/payment/cardstream.php#L122-L126
https://github.com/cardstream/OpenCart/blob/eb4fa6202274a416ccd7035ecf75c6c9a0232373/httpdocs/catalog/controller/payment/cardstream.php#L327-L335

I hope this is satisfactory :)

**Comment by philpandco** [comment]
Great, thanks!

Cheers,

Ben
